* Files
** Loading and saving
*** Tramp Setup
**** TODO magic here to do The Right Thing (tm) for tramp, regardless of what OS is being used to execute it. 
**** TODO the best mode (scp? ssh? something else?) should be set as the default.
**** Set tramp up to play nicely with NixOS
#+name: tramp
#+begin_src emacs-lisp
(require 'tramp) 
(add-to-list 'tramp-remote-path "/var/run/current-system/sw/bin")
#+end_src

* Transient mark mode

  For now Transient Mark mode is just turned off.  I don't like
  transients.

  Seriously though, the reason why I like not having transient mark
  mode is that I have gotten into the habit of dropping marks and
  using the mark ring.  I also use the mark for nagivation, and having
  transient mark mode on messes with my workflow.

  If you are opposite, then let me know (file a bug report:
  https://github.com/jonnay/emagicians-starter-kit/issues/new) and
  I'll fix the emagicians kit so that transient mark mode can be
  easily activated.

#+name: turn-off-transient-mark
#+begin_src emacs-lisp
  (transient-mark-mode -1)
#+end_src

* Killing and yanking
** Swap region with kill ring
** Insert-yank-as-rectangle
** when yanking, indent according to the mode
#+begin_src emacs-lisp
(defadvice yank (after indent-region activate)
  (if (member major-mode programming-modes)
	  (indent-region (region-beginning) (region-end) nil)))
#+end_src

* Indenting and tabbing 
  I am not going to solve this for everyone and try to be all things for all peope.  In fact I will bet money that my style of indentation kinda sucks, and look to the emacs community to help me to stop sucking.
#+begin_src emacs-lisp
(set-default 'tab-width 4)
#+end_src

#+name fix-defaults
#+begin_src emacs-lisp
(set-default 'c-basic-offset tab-width)
(set-default 'cperl-indent-level tab-width)
(set-default 'nxml-child-indent tab-width)
#+end_src
** Change Behavior of the home key
   Home should jump between the level of indendation and the first line 

*** Shamelessly hacked from Drew Adams. 
#+begin_src emacs-lisp
(defun emagician-beginning-or-indentation (&optional n)
  "Bounce cursor to beginning of this line or to its indentation."
  (interactive "P")
  (cond ((bolp) 
         (back-to-indentation))
        ((save-excursion (skip-chars-backward " \t") (bolp)) ; At indentation.
         (forward-line 0))
        (t (back-to-indentation))))
#+end_src
*** Do key map 
#+begin_src emacs-lisp
(global-set-key [home] 'emagician-beginning-or-indentation)
(substitute-key-definition 'beginning-of-line 'beginning-or-indentation global-map)
#+end_src

** Make sure end key always goes to end of hte line
#+begin_src emacs-lisp
(global-set-key [end] 'end-of-line)
#+end_src

* Snippets. 

#+name: 
#+begin_src emacs-lisp
  (emagician-expect-package 'yasnippet)
  (require 'yasnippet)

  (yas/load-directory (expand-file-name "snippets" emagician-dir) t)
  
    (defun yas/org-very-safe-expand ()
      (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))
    
    (defun yas/org-setup ()
      ;; yasnippet (using the new org-cycle hooks)
      (make-variable-buffer-local 'yas/trigger-key)
      (setq yas/trigger-key [tab])
      (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
      (define-key yas/keymap [tab] 'yas/next-field))
    
    (add-hook 'org-mode-hook #'yas/org-setup)

#+end_src

