* A
  - [[file:Emagician.org::*Assets][Assets]]
* C
  - [[file:Emagician.org::*Entity Customization][customization]]
* D
  - [[file:Emagician.org::*Breakage Helpers][debugging]]
  - [[file:Emagician.org::*Turn off debugging][debugging]]
* I
  - [[file:Emagician.org::*Breakage Helpers][initialization]]
  - [[file:Emagician.org::*Emagician/load][initialization]]
* L
  - [[file:Emagician.org::*Load Paths, Custom Files, etc.][load-path]]
  - [[file:Emagician.org::*Emagician Starter Kit has it's own Helper Functions][loading]]
* P
  - [[file:Emagician.org::*Package Archives setup][packages]]
  - [[file:Emagician.org::*Package Management][packages]]
* S
  - [[file:Emagician.org::*Pre-Scratch-Links][scractch-links]]
  - [[file:Emagician.org::*Scratch messaging][scratch]]
  - [[file:Emagician.org::*Now set it to our Baseline beautified "you're-busted" text][scratch]]
  - [[file:Emagician.org::*Use the new improved emagician scratch.][scratch]]
  - [[file:Emagician.org::*Initiate thee scratch][scratch]]
